### ISSUE TITLE
Why allow connections only from loopback interface?

### ISSUE THREAD

**Issue by sisao** [indyjo/bitwrk#150]
If i run this 
>  ./bitwrk-client.exe -intiface 192.168.100.1
 
I would expect that I can access the ui via 192.168.100.1:8081 but instead I get

> Access only allowed from loopback interface, not from 192.168.100.1:64465

Is this correct?

https://github.com/indyjo/bitwrk/blob/0ff9cdec7b232cebc4ceea00dd96c2d045854508/src/github.com/indyjo/bitwrk-client/cmd/bitwrk-client/client_main.go#L195

**Comment by indyjo** [comment]
Admittedly, that's a little confusing. Thanks for asking!

Even if you let BitWrk listen on external network interfaces, it will still only allow connections from localhost (local interfaces) for UI functions. It's a basic safety measure because you can easily start BitWrk from Blender with the option "Allow other computers as workers" and this shouldn't lead to the computer becoming exposed.

That said, anything other than listening on *all* interfaces using

      bitwrk-client.exe -intiface ""
probably doesn't make a lot of sense.

**Comment by sisao** [comment]
Thx for explanation...
