### ISSUE TITLE
Implement chart for cost on local account-page

### ISSUE THREAD

**Issue by Mobilpadde** [indyjo/bitwrk#195]
It'd be neat if the [chart/graph of price/demand](https://bitwrk.net/#placeholder-1) would be shown on localhost. Easier to manage pricing and such :dancer:

**Comment by indyjo** [comment]
The underlying issue is, how can we help users in setting a "good" price?

The problem with the price chart, as on the home page, is that it doesn't tell anything for when there hasn't been any activity for some time. We could try with a [market depth chart](https://hackernoon.com/depth-chart-and-its-significance-in-trading-bdbfbbd23d33) but it's harder to read.

in #172 we're suggesting to give the user a choice of price on a scale, based on statistics over past trades. Something like

- Economy: 25-percentile of past prices
- Recommended: 50-percentile (median) of past prices
- Priority: 75-percentile of past prices

This would suggest a meaningful price and create some price stability. Also, it can be extended to be an auto-adapting algorithm where participants automatically adjust prices to changes in supply and demand.

This could be implemented in the Blender UI, removing the need for the user to switch to the web UI (something that some users had difficulties understanding).

If BitWrk gets successful enough that there is constant activity, we can consider the traditional price chart again. It's good for seeing trends after all.

**Comment by Mobilpadde** [comment]
Oh, that makes sense!

One thing though, please do not remove the web UI, I think it'll still provide meaning in the future, even though, if it all will get implemented in Blender :+1:
